import type { Metadata } from "next";
import "./globals.css";
import type React from "react";
import { AppLayout } from "@/components/app-layout";
import { AppProviders } from "@/components/app-providers";

export const metadata: Metadata = {
  title: "Dealforge",
  description: "Generated by create-solana-dapp",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"scroll-smooth antialiased"}>
        <AppProviders>
          <AppLayout>{children}</AppLayout>
        </AppProviders>
      </body>
    </html>
  );
}

declare global {
  interface BigInt {
    toJSON(): string;
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString();
};
