export function AppFooter() {
  return (
    <footer className="bg-neutral-100 p-2 text-center text-xs dark:bg-neutral-900 dark:text-neutral-400">
      Generated by{" "}
      <a
        className="link hover:text-neutral-500 dark:hover:text-white"
        href="https://github.com/solana-developers/create-solana-dapp"
        rel="noopener noreferrer"
        target="_blank"
      >
        create-solana-dapp
      </a>
    </footer>
  );
}
